name: build and run tests

on:
  push:
   branches: [ cicd ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: install Ninja
        run: choco install ninja
      - uses: actions/checkout@v3
      - name: Install boost
        uses: MarkusJx/install-boost@v2
        id: install-boost
        with:
         boost_version: 1.84.0
         link: static
         platform_version: 2022
         toolset: mingw
         cache: false
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.0'
          arch: 'win64_mingw'
      - name: Running cmake
        run: |
          mkdir build
          cd build
          cmake -G Ninja ..
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
      - name: Running ninja
        if: success() || failure()
        run: |
          cd build
          ninja